### ISSUE TITLE
Client crash when using Exchanger with Cathedral pillar

### ISSUE THREAD

**Issue by LemADEC** [Direwolf20-MC/BuildingGadgets#323] opened 2019-06-28 21:47 UTC
* Forge version 14.23.5.2838
* Building Gadgets version 2.6.8
- Cathedral version 1.12.2-1.9.7k
* https://gist.github.com/LemADEC/62ac8e96d130ae69dd4924b5b7c3079f
* How to reproduce the issue
Get an Exchanger and set it to the Cathedral mod's Dwarven pillar
Trying to use it or change it causes a crash

**Comment by MichaelHillcox** [comment] 2019-07-01 18:34
Hi, thanks for your issue. I've reviewed your error log and done my own testing. I have found what is causing the issue but it would appear to be caused by Cathedral mod returning null on `getQuads` of which should not be happening. 

This causes our renders not to know what to do. I do not do much with rendering so @MajorTuvok may be able to give a definitive answer on this but from what I can see this is an issue on the other mods side and would request you open an issue on their GitHub with a reference to this issue here. They may be able to shine some light on who's issue it truly is. It could be that we're not supporting something specific.

I have, on the other hand, taken the time to stop something like this causing a crash in the future and this can be seen here https://github.com/Direwolf20-MC/BuildingGadgets/commit/0de8efe4d33b7135c1041c193a5a391f92c73c45 

For now I'm going to close this issue and queue the 'fix' to be released in our next version.

**Closed by MichaelHillcox** 2019-07-01 18:34 UTC
Labels: 1.12, incompatibility, third party issue

**Comment by LemADEC** [comment] 2019-07-01 19:56
I'm a bit confused on the relation between `getQuads` returning null and the referenced commit 0de8efe that is catching exceptions related to `renderBlockBrightness`. Can you elaborate?

**Comment by MajorTuvok** [comment] 2019-07-01 20:47
The name `RenderBlockBrightness` is propably a bit confusing: It just renders the sepcified Block with the specified brightness. In order to render it you of course need to call getQuads as you can't render quternions without actually knowing them...

**Comment by MajorTuvok** [comment] 2019-07-01 20:52
Also @MichaelHillcox mentioned to me that he was getting a different exception then the one you posted... I presumed he fixed that...
I also thought that we put a horrible 'fix' (catching Exception! :( ) out there for the exact same IllegalState before, but I don't remember where or when.

**Comment by LemADEC** [comment] 2019-07-01 21:07
The `IllegalStateException: Not building!` exception supposedly comes from `finalizeDrawing()` in Forge.
I don't see how it's related to `renderBlockBrightness`, I wonder if another mod is messing things up here.

**Comment by MichaelHillcox** [comment] 2019-07-01 21:12
I'm not following. The issue comes from us passing a blockstate that when read leads to a method, in this case, getquads, of which returns null. This in turn tries to be ready by a inner method of `renderBlockBrightness`. It's really not that complicated.

**Comment by MajorTuvok** [comment] 2019-07-02 14:13
@MichaelHillcox if you look at the provided stacktrace: There's again the `not building` `IllegalStateException`. Not an NPE.

**Comment by MichaelHillcox** [comment] 2019-07-02 14:16
That is caused closer to the top of the call stack. If you go back further you find out why the illegalStateException happens.

**Comment by MajorTuvok** [comment] 2019-07-02 15:13
Well it sadly doesn't show that in the provided and therefore presumably incomplete log...

**Comment by MichaelHillcox** [comment] 2019-07-02 15:49
The log was slightly wrong as it was an error after the main error. Check out the linked commit and you'll see I've added a try catch for the null pointer I found and improved the try catch for the rendering methods. This is all we can do as the issue comes from a malformed state and the state in question has an issue with getquads. This is what causes the null pointer and the render is what causes ISE
