### ISSUE TITLE
1.14.4 Client Crash

### ISSUE THREAD

**Issue by Wissi** [Direwolf20-MC/BuildingGadgets#382] opened 2019-09-20 04:19 UTC
While using the building tool in creative to fill with grass blocks it crashed.
* Forge version: 28.1.10
* Building Gadgets version: buildinggadgets-3.0.5
* A link to the crash report is [here](https://gist.github.com/Wissi/02dc979dbf43cbe8de965c134975c72b).
* How to reproduce the issue: use building gadget to place grass block to fill a space.

Error: 
```
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at com.direwolf20.buildinggadgets.client.renderer.EffectBlockTER.render(EffectBlockTER.java:44) ~[?:3.0.5] {}
	at com.direwolf20.buildinggadgets.client.renderer.EffectBlockTER.func_199341_a(EffectBlockTER.java:18) ~[?:3.0.5] {}
```

**Comment by MajorTuvok** [comment] 2019-09-20 06:37
Duplicate of #375

**Closed by MajorTuvok** 2019-09-20 06:37 UTC
