### ISSUE TITLE
Exchanging Gadget + Botania Copy Paste

### ISSUE THREAD

**Issue by douyabian** [Direwolf20-MC/BuildingGadgets#524] opened 2020-09-01 04:30 UTC
MC Version: 1.16.1
Modpack: Enigmatica 6
Forge vers: Forge 32.0.108
BG Vers: Building Gadgets 3.5.1

Issue 1: Exchanging Gadget with dank storage only returns 1 block into the dank storage

Issue 2: Copy paste gadget, copy-pasting botania blocks caused the game to crash

Steps: 
Copy an area with a Mana Pool
Paste area
Crash

Crash logs:
https://pastebin.com/raw/FkXY8ig1
https://pastebin.com/raw/Ru82szxv

Edit: Went back in game, a whole bunch of invisible Effect Blocks were in place of where things are supposed to be pasted to

**Comment by MajorTuvok** [comment] 2020-09-01 07:18
Interestingly these are client side crashes and not Server crashes (GameRenderer)... I guess the EffectBlocks remain behind because in SinglePlayer the Internal Server is shut down alongside the client? :shrug:

Thanks for the report.

**Comment by hvdklauw** [comment] 2020-09-01 19:32
Issue 1: Can't reproduce, had 1 cobble in my dank storage, replaced 9 placed cobble with dirt and ended up with 10 cobble in my dank storage, are you sure you didn't have a tier 1 dank storage set to VOID_PICK with 255 items in it? because then it would add 1 and void the rest.

**Comment by hvdklauw** [comment] 2020-09-01 19:37
The second issue I got a crash too: https://pastebin.com/raw/tSZ8m65n

**Comment by MichaelHillcox** [comment] 2020-10-24 18:59
Fixed for 1.15

**Comment by MichaelHillcox** [comment] 2020-10-30 18:21
Fixed will be released soon :+1:

**Closed by MichaelHillcox** 2020-10-30 18:21 UTC
Labels: 1.16, bug
