### ISSUE TITLE
Horizontal/Vertical Flipping/Mirroring for Copy/Past Gadget

### ISSUE THREAD

**Issue by jtgraphic** [Direwolf20-MC/BuildingGadgets#258] opened 2019-03-05 03:46 UTC
It would be able to flip/mirror the template in a copy/paste tool for doing symmetrical builds.

**Comment by Phylogeny** [comment] 2019-03-05 04:39
Pastes can already be mirrored horizontally, as per af204debcd42f25dd250be0fbecc534695388111, but vertical rotation/mirroring should be considered.

**Comment by jtgraphic** [comment] 2019-03-05 06:04
Oh thanks. Clearly I just need to update my version.

**Comment by Phylogeny** [comment] 2019-03-05 06:06
That feature is currently unreleased, actually, but it will be soon.

**Comment by Phylogeny** [comment] 2019-03-18 12:51
Horizontal mirroring added in v2.6.7 (vertical rotation/mirroring has not yet been fully considered)

**Comment by MajorTuvok** [comment] 2019-09-01 17:48
Duplicate of #305

**Closed by MajorTuvok** 2019-09-01 17:48 UTC
Labels: enhancement
