### ISSUE TITLE
World freezes (extreme tick lag) when using Gadgets

### ISSUE THREAD

**Issue by Dimentive** [Direwolf20-MC/BuildingGadgets#287] opened 2019-04-18 09:54 UTC
When I used my exchanging gadget to replace a few blocks of diorite with stone from my inventory, the server froze (i.e., the server side, not the client side; I’m playing singleplayer). I couldn’t interact with the world or write in the chat (although I could move around). After a few minutes, the server unfroze, and I noticed that my TPS went down to ~7 and mean tick time went up to ~385 ms during this freeze. The stone blocks were replaced, and I tried to use the exchanging gadget again, thinking that it was just a one-off thing, but it happened again. This time, the server-side of the game never unfroze, so I had to exit and re-enter the world.

I’ve used the exchanging and building gadgets many times before, and this has never happened until now.

**Relevant part of log:** https://pastebin.com/raw/7P1cK59T

My client didn’t crash, so I didn’t get a crash report; the server froze.

#### Versions

* **Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version [1.65a](https://minecraft.curseforge.com/projects/enigmatica2/files/2700051), latest), with some mods added ([list](https://pastebin.com/raw/gDYGbpfi))
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2781
* **Building Gadgets:** [2.6.8](https://minecraft.curseforge.com/projects/building-gadgets/files/2691133) (latest)

**Comment by MajorTuvok** [comment] 2019-04-18 10:26
A quick overview shows that there are exceptions occuring **client-side**

**Comment by MichaelHillcox** [comment] 2019-04-18 19:15
It's weird that they're all missing file issues. Also depending on the area exchanged, lag spikes are to be expected.

**Comment by Dimentive** [comment] 2019-04-18 20:47
I noticed that when I exchanged the diorite blocks to stone, they, after the first lag spike was over, there were invisible blocks rather than stone blocks where the diorite blocks had been. They weren’t air blocks either, as they had outlines.

By the way, I didn’t exchange many blocks. The radius of the exchanging gadget was set to 5 blocks, and the actual area was even smaller than that. I’ve exchanged much larger areas before with no problem. And the fact that I tried to replace vanilla blocks (diorite) with vanilla blocks (stone) is pretty strange as well. I’m not sure what caused this, but I’m now scared to use any gadget from this mod, which is a shame, as they are more useful than anything else in my arsenal.

**Comment by Dimentive** [comment] 2019-04-19 04:39
I tried using the exchanging gadgets again and experienced no issues this time.

**Comment by MajorTuvok** [comment] 2019-04-21 10:06
I'm pretty sure that this is some sort of incompat, as it does not happen to me in minimal dev enviornment

**Comment by Dimentive** [comment] 2019-04-21 12:13
It happened again when I was in the same place as before. That place is near my large wall of storage drawers, all of which with thousands of items in them, from the [Storage Drawers](https://minecraft.curseforge.com/projects/storage-drawers) mod. This didn’t happen elsewhere in my base, so it could have something to do with my storage drawers.

When this happens, the blocks I replace blocks with are invisible for a while until my world is unfrozen:

![Invisible stone (cropped screenshot)](https://user-images.githubusercontent.com/34230933/56469838-35369e80-643f-11e9-90fa-2ac1ca9262b6.png)

My tick time also gets really high, and my TPS gets really low.

![TPS drop - Building Gadgets](https://user-images.githubusercontent.com/34230933/56469839-35369e80-643f-11e9-85c4-a61d10145ce1.png)

**Comment by MichaelHillcox** [comment] 2019-04-21 12:15
I've tried to reproduce your issue but I can't seem to do it. Are you in single player or mp? Why are you using optifine with 3 other client side implement mods? Does this open happen near your base?

**Comment by Dimentive** [comment] 2019-04-21 12:20
>Are you in single player or mp?

Single-player.

>Why are you using optifine with 3 other client side implement mods?

To improve my performance. OptiFine reduces a lot of stuttering that I was having before I added it.

>Does this open happen near your base?

It only happens near my storage drawers, as mentioned.

**Comment by MichaelHillcox** [comment] 2019-04-21 12:21
So no more freezing away from the draws

**Comment by Dimentive** [comment] 2019-04-21 12:27
No, I’ve only experienced it (three times) when I’ve replaced blocks near my storage drawers but never anywhere else in my base or the world.

**Comment by MichaelHillcox** [comment] 2019-04-21 12:32
Interesting

**Comment by MajorTuvok** [comment] 2019-04-21 15:27
Did you bind the drawers?

**Comment by Dimentive** [comment] 2019-04-21 15:59
Yes, all the drawers are connected to one drawer controller, if that’s what you mean.

I’m fully able to use the building and exchanging gadgets elsewhere in my base, but it always freezes my world when I do it near the drawers. There are other things in the chunk, so it may not be the drawers, but if I were to guess, I’d say it’s the drawers.

**Comment by MajorTuvok** [comment] 2019-04-21 16:00
I meant did you bind the Gadgets to the drawers, but according to your comment, I presume you did not.

**Comment by Dimentive** [comment] 2019-04-21 18:41
Oh. Do you mean if I shift-right-clicked one of the drawers with the exchanging gadget (unless there’s some way to bind gadgets to tile entities with inventories that I’m unaware of)? I didn’t do that. I simply tried to replace a few diorite blocks with stone blocks. I didn’t select any of the drawers, nor did I try to replace them with the gadget.

**Comment by Dimentive** [comment] 2019-04-21 19:27
It just happened again, this time elsewhere in my base, not in the same area as the storage drawers. This time, I didn’t even replace any blocks with the exchanging gadget. I simply opened the exchanging gadget’s GUI and changed its range, which causes my world to freeze for minutes every time I do so.

It looks like this doesn’t have anything to do with storage drawers after all. I can still use the building gadget just fine everywhere in my base, including in the room with my storage drawers, but I can’t use the exchanging gadget. In fact, when I said earlier that I could use it elsewhere in my base, I think I might’ve just been thinking of the building gadget. My world freezes every time I use the exchanging gadget, regardless of where I am in my base.

**Comment by Dimentive** [comment] 2019-04-21 19:28
It just happened again, this time elsewhere in my base, not in the same area as the storage drawers. This time, I didn’t even replace any blocks with the exchanging gadget. I simply opened the exchanging gadget’s GUI and changed its range, which causes my world to freeze for minutes every time I do so.

It looks like this doesn’t have anything to do with storage drawers after all. I can still use the building gadget just fine everywhere in my base, including in the room with my storage drawers, but I can’t use the exchanging gadget. In fact, when I said earlier that I could use it elsewhere in my base, I think I might’ve just been thinking of the building gadget. My world freezes every time I use the exchanging gadget, regardless of where I am in my base. As I’ve said before, this didn’t use to happen; it’s something that started happening only recently.

**Comment by MajorTuvok** [comment] 2019-04-21 19:42
Honestly I have no idea what's happening there... Sorry

**Comment by Dimentive** [comment] 2019-04-21 20:03
That’s a shame.

**Comment by MichaelHillcox** [comment] 2019-04-21 20:04
Try without optifine?

**Comment by Dimentive** [comment] 2019-04-21 20:05
All right, I’ll try that tomorrow.

**Comment by MichaelHillcox** [comment] 2019-05-24 18:09
I'm going to go on a whim here and assume that this was caused by an issue from a different mod and thus has now been fixed by the other mod author. If you continue to have this issue then please re-open this issue and we'll continue to investigate.

**Closed by MichaelHillcox** 2019-05-24 18:09 UTC
Labels: 1.12, bug, incompatibility
