### ISSUE TITLE
(1.12.2) poof! crashes

### ISSUE THREAD

**Issue by Migmag789** [Direwolf20-MC/BuildingGadgets#74] opened 2018-08-29 10:17 UTC
Hey Direwolf20 ! I love your mod. Now I use it everytime I play somewhere. But... it crash. I was playing my modpack, and the mod crashed. I was in a server, I crashed, but the server did nothing. I guess that's a client side problem... Please, fix it and thank you for your awesome mod !
Forge : 14.23.4.2757
Building Gadgets : 1.6.2
(for the modpack I'm using Beyond the skies 1.6.1)

Good job ! :D

**Comment by Tahakk** [comment] 2018-08-29 10:41
It is nice that you report a crash, just include crashlog mate

**Comment by Migmag789** [comment] 2018-08-29 12:03
https://paste.dimdev.org/kufefifahe.mccrash Oops sorry I forgot to add it... ;(

**Comment by Tahakk** [comment] 2018-08-29 12:11
This looks much like #66, take a look at that please if there is solution for you

**Comment by Direwolf20-MC** [comment] 2018-09-04 01:15
Should be fixed in 2.0 :)

**Closed by Direwolf20-MC** 2018-09-04 01:15 UTC

**Comment by Phylogeny** [comment] 2019-02-02 13:21
Duplicate of #55
