### ISSUE TITLE
ObjectHolder being applied after ColorHandler.Block event crashes game in some cases

### ISSUE THREAD

**Issue by Sunekaer** [Direwolf20-MC/BuildingGadgets#335] opened 2019-07-30 16:40 UTC
* Forge version 1.14.4 28.0.24
* Building Gadgets version 3.0.0
* crash report https://paste.feed-the-beast.com/view/eaeb4d62
* How to reproduce the issue
Launch the game, doesn't happen every time.

**Comment by MajorTuvok** [comment] 2019-07-30 16:43
I was about to update to Forge .24 - I guess I'll start experiencing it then -_-

**Comment by MajorTuvok** [comment] 2019-07-30 16:45
Actually this is a Forge Bug: The line you are referencing can only throw a NPE if the event is null

**Comment by MajorTuvok** [comment] 2019-07-30 16:47
What is kind of perculiar, is that this line references an ObjectHolder

**Comment by MajorTuvok** [comment] 2019-07-30 16:57
So I tried starting the game 10 times in a row now and couldn't reproduce this crash. How often do you experience this? Does it even happen with only BuildingGadgets present?

**Comment by Sunekaer** [comment] 2019-07-30 17:00
Current modlist: https://s1.sunekaer.com/files/modlist.html 
Happens like every 2second launch
ill test with only BuildingGadgets present?

**Comment by MajorTuvok** [comment] 2019-07-30 17:02
I'd apreciate it, If you could test with only BuildingGadgets... I fail to reproduce this in dev... :(

**Comment by Sunekaer** [comment] 2019-07-30 17:13
cant recreate with only BuildingGadgets, ill update the issue, when/if i find what mod causes it

**Comment by MajorTuvok** [comment] 2019-07-30 17:13
Ok, thanks

**Comment by Sunekaer** [comment] 2019-07-30 17:24
Torchmaster-2.0.0.3-alpha

**Comment by Sunekaer** [comment] 2019-07-30 17:25
https://www.curseforge.com/minecraft/mc-mods/torchmaster/files/2751474
So if the issue is on your side or their idk

**Comment by MajorTuvok** [comment] 2019-07-30 17:26
Errr... Ok... That's weird

**Comment by MajorTuvok** [comment] 2019-07-30 17:26
Thanks

**Comment by Sunekaer** [comment] 2019-07-31 16:49
Seems to be fixed by the new TorchMaster update

**Comment by MajorTuvok** [comment] 2019-07-31 17:48
Ok, Thanks for the notice

**Comment by MajorTuvok** [comment] 2019-07-31 17:49
I'll close it then

**Closed by MajorTuvok** 2019-07-31 17:49 UTC
Labels: 1.14, bug, incompatibility, third party issue
