### ISSUE TITLE
Server 1.14.4 crashing on startup.

### ISSUE THREAD

**Issue by Wissi** [Direwolf20-MC/BuildingGadgets#364] opened 2019-09-04 07:58 UTC
Love your work.

We are porting over our servers to 1.14.4 and are having the serve crash with this mod. 
Removing mod and server is working fine.
Full crash log [here](https://gist.github.com/Wissi/c04e0e5fa74c6a072f4d02589147378d).
Full "debug" log [here](https://gist.github.com/Wissi/751f43f5370e75471c1f7e34cb727a2c).

* Forge-28.0.81.jar
* buildinggadgets-3.0.5.jar

Thanks you for you great work.

**Comment by MajorTuvok** [comment] 2019-09-04 08:08
Update your Forge version this is not our issue

**Comment by MajorTuvok** [comment] 2019-09-04 08:09
Duplicate of #360

**Closed by MajorTuvok** 2019-09-04 08:08 UTC

**Comment by Wissi** [comment] 2019-09-04 08:27
Well unfortunately it is your code that's breaking it. 
Forge is at ver .91 right now and still happens.  Full crash log [here](https://gist.github.com/Wissi/b0e56f53c5b5e89b7c06a4fd09288c0d).
`¯\_(ツ)_/¯`

Using:
Forge-28.0.91.jar     (Latest available on Forge right now)
buildinggadgets-3.0.5.jar

Maybe now you can find a solution so we can all enjoy this great mod on our servers.

**Comment by MajorTuvok** [comment] 2019-09-04 08:29
REmove the other mods and try again - I'll verify again if you ask me too... But this is not our Problem

**Comment by Wissi** [comment] 2019-09-05 02:57
It is not a duplicate of #360 since they have **server wide** issues (makes me think they have no idea what they are doing) and we have a stable working server with 118 mods working perfectly fine.

They created and "issue" with Forge (which is not even addressed as it has no relevant information), which I'm sure you read in the interest of keep up with issues?

We are trying to help you get your mod out, working with modpacks and server environment.
Obviously it's a compatibility issue w/other mod(s).
We have found that if **any** of these mods are installed: (small number of mods used for sample)
[Cosmetic Armor Reworked](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[CraftingCraft](https://www.curseforge.com/minecraft/mc-mods/craftingcraft)
[Camera Mod](https://www.curseforge.com/minecraft/mc-mods/camera-mod)
Building Gadgets crashes the server with the same msg always:
```
java.lang.IllegalStateException: The ObjectHolder annotation cannot apply to a field that does not map to a registry. Ensure the registry was created during the RegistryEvent.NewRegistry event. (found : com.direwolf20.buildinggadgets.api.serialisation.ITemplateSerializer at com.direwolf20.buildinggadgets.api.serialisation.SerialisationSupport.DELEGATING_TEMPLATE_SERIALIZER)
```
Yet all these mods work perfectly fine together, so it "must" be forge? 
(even after using the latest versions of Forge, a I stated above)

Yet it's not your problem?
Well,  "If" Forge ever gets their act together (since it's their problem), we might try this mod again.

Thanks anyways.

**Comment by MajorTuvok** [comment] 2019-09-05 04:36
Thanks for finding the incompatible mods... 

You have obviously no idea what the mentionied issue is even about - It is a duplicate of the Mentioned issue, because it has a similiar suite of mods and **the same crash**! The reason why I said this is Forge's Problem is that I simply cannot do anything if they don't send me the event! Of course it's going to crash!
Something in these other mods results in us not recieving the `RegistryEvent.NewRegistry` event...

**Comment by MajorTuvok** [comment] 2019-09-05 16:38
A note for @Wissi CraftingCraft and Cosmetic Armor Reworked throw exceptions during Registry loading (which result in us not recieving RegistryEvents...) - I'll report them tomorrow and link them for you

**Comment by Wissi** [comment] 2019-09-06 14:21
FYI   Forge-28.0.93 has "fixed" the issue (or made it not crash) and current mod is working fine now.
We'll report back if anything goes wrong again, since Forge is still progressing to a stable version,.

**Comment by MajorTuvok** [comment] 2019-09-06 14:23
Interesting - seems like something lex touched whilst working on REGISTER packet encode/decode had a side effect on this
