### ISSUE TITLE
[BUG REPORT] Block Duplication w/ Building Gadget in offhand slot

### ISSUE THREAD

**Issue by Necrolythe** [Direwolf20-MC/BuildingGadgets#130] opened 2018-11-08 12:27 UTC
Pack: Stoneblock

Issue: Using Building Gadget in offhand slot to place multiple blocks, then veinmining with Diamond Hammer results in duplication of original resource (Gravel) and production of hammered resource (Dirt)

**Comment by Phylogeny** [comment] 2018-11-08 12:53
Are you saying that when you place the blocks in the world with the building gadget, the materials are not taken from your inventory? If so, what does vein mining and hammers have to do with this?

Or are you instead saying that the materials are taken from your inventory, but that vein mining them in-world with a hammer causes twice the expected resource to drop? If so, would that not simply implicate vein miner and/or the hammer? Have you tried placing the blocks without the building gadget, then vein mining them with the hammer?

**Comment by Necrolythe** [comment] 2018-11-08 12:57
so, went with some further testing

Placing with gadget in offhand then veinmining with pickaxe: blocks reappeared in inventory and did not drop in world

placing with gadget in offhand: blocks consumed from inventory, and placed in world

The hammer from Ex Nihilo converts blocks in world through a tier list (Stone --> Cobble --> Gravel --> Dirt, etc)

It seems like BG is treating offhand use followed by breaking as if it was the Undo command, but on a block by block basis

**Comment by Necrolythe** [comment] 2018-11-08 12:58
Should be noted that only the amount of blocks placed is returned. So if you use a stack of Cobble, then hammer it all to turn it into Gravel, the original Cobble stack is refunded, along with a stack of Gravel

So, doesn't duplicate the source material, just the output

**Comment by Direwolf20-MC** [comment] 2018-11-09 00:34
I was able to replicate the bug, looking into why its happening now!

**Comment by Direwolf20-MC** [comment] 2018-11-09 03:03
I'm about 90% sure this bug is more on Ex Nihilo's side. Basically what is happening:
I use a blockbreak event to say that if you're breaking a block with one of my tools (Which is how Undo works), to just put the dropped items directly into the inventory, and remove them from the list of dropped items

Ex Nihilo is seeing that you're breaking a block, checks what the block in the world is, and then decides to add the new item to the dropped items list (So if its cobble -> Clear the dropped items list, and then add gravel to the list). 

The bug occurs because Ex Nihilo doesn't check to see if the dropped items list is empty before the clear / add. The best way to solve this (In my opinion) is for ex nihilo to confirm that someone else hasn't intercepted the dropped items before they get to it. 

I might be doing something wrong too of course ;). But I'm pretty sure this is accurate. Closing as a cross-mod compatibility issue that I think needs to be fixed on their side.

**Closed by Direwolf20-MC** 2018-11-09 03:03 UTC

**Comment by MajorTuvok** [comment] 2018-11-09 06:02
@Direwolf20 I just looked through you're code and couldn't find a check for whether the BlockBreak Event is actually caused by an undo Operation. This should result in the item being duplicated as soon as any mod adds something to the dropped item list and thereby creates a second Item, when a GenericGadget is in any hand.

ExNihilo is doing just fine, they are completly clearing the Drop-List when a Hammer was used. It's just impossible to detect/prevent, that you're giving the player an Item directly into his Inventory.

Suggested fix: Add some nbt value which is set to a List of undo Blocks and then when blocks with an GenericGadget in hand (which is currently the only check to see if it was caused by an undo Operation as far I can tell) are broken: iterate over the List and look whether this Item was undone and should therefore be given back.
