### ISSUE TITLE
Add MOVE to COPY & PASTE

### ISSUE THREAD

**Issue by IngmarBitter** [Direwolf20-MC/BuildingGadgets#470] opened 2020-04-24 17:14 UTC
When building functional houses I frequently find that the interior dimensions are not having enough space for the chests or machines to fit. So I want to enlarge my house a little. I.e. just move one wall out by a block or two. I could **copy** the wall, then cut it down to get the parts and then **paste** it. But that is a lot of effort and maybe not all parts fit in my inventory.  It would be nice to have a third radial menu entry for **move**. The workflow would be to start with **copy** and mark the wall with all its creases and windows. Then select **move** and place as one would with paste, only that the blocks are not taken from my inventory but instead from their current world location.  

The **move** would have to work when source and destination are partially overlapping (move a 3 blocks thick wall by one block).  Should not be a problem as long as first all source blocks are removed, or if done one at a time, the iteration is such that it starts with the slice of the volume of interest that is not overlapping (there always must be at least one) and when it is done then there is another one where the destination has just beer cleared and source blocks can be moved to now.

**Comment by MajorTuvok** [comment] 2020-04-25 06:52
Duplicate of #266

**Closed** 2020-04-25 10:08 UTC
