### ISSUE TITLE
Charging Station charges without fuel

### ISSUE THREAD

**Issue by NillerMedDild** [Direwolf20-MC/BuildingGadgets#332] opened 2019-07-27 18:59 UTC
- Forge 1.14.4-28.0.13
- buildinggadgets-3.0.0

The Charging Station produces energy without fuel.
Below screenshot is of a Charging Station I placed about 5 seconds prior to taking the screenshot.
![billede](https://user-images.githubusercontent.com/21295394/61998501-73cc9c80-b0b1-11e9-9369-627bc39a9936.png)

**Comment by MichaelHillcox** [comment] 2019-07-27 19:00
Interesting. Any other mods present?

**Comment by NillerMedDild** [comment] 2019-07-27 19:02
Yup, quite a few: https://gist.github.com/NillerMedDild/9eb788e7e883927012eddb6f224d30db

**Comment by MajorTuvok** [comment] 2019-07-27 19:02
That's very perculiar, as it didn't happen in dev

**Comment by MichaelHillcox** [comment] 2019-07-27 19:03
Question, do you have anything in your inventory that would charge items?

**Comment by NillerMedDild** [comment] 2019-07-27 19:03
Ah alright, I'll try removing some mods and see if I can pin it down.

Nope, empty inventory.

**Comment by MichaelHillcox** [comment] 2019-07-27 19:04
Alright, that's just weird. I'll have a look into it 👍

**Comment by MichaelHillcox** [comment] 2019-10-25 09:45
Never been able to get this to happen on my end but I've actually fixed a few fatal issues with this block so hopefully it'll be fixed in 3.0.7+

**Comment by MajorTuvok** [comment] 2019-10-25 10:15
I actually had it happen once (yesterday) using the latest charging station. I was sadly unable to reproduce a second time though.

**Comment by MichaelHillcox** [comment] 2019-10-25 11:04
Something's wrong but we can't fix it without finding out why. Well just have to close this and wait for it to be reported again but with reproduction steps.

**Closed** 2019-10-26 17:23 UTC
Labels: 1.14, bug, pending release
