### ISSUE TITLE
A library function for the Copy-paste gadget

### ISSUE THREAD

**Issue by Kegulf** [Direwolf20-MC/BuildingGadgets#489] opened 2020-06-22 16:10 UTC
# A library function for the Copy-paste gadget 
You could grab most of the `Template Manager` UI and add it to the copy-paste gadget 😁 
Add a `ListView` to display all available `saved-structures` and you're onto something 👌 

This would allow it to come with a set of default blueprint / saved-structures like:
- Tinkers smeltery
- Thaumcraft altar
- Well any altar or multiblock-structure 😄 

Not sure how the blueprint data is saved, is it compressed? Might need to be if this becomes a reality 😁

**Comment by MajorTuvok** [comment] 2020-06-23 15:45
Last state I remember is that such a list was intended for a seperate block

**Comment by MajorTuvok** [comment] 2020-06-23 15:45
> You could grab most of the Template Manager UI and add it to the copy-paste gadget
I don't think this is a good idea, you'd essentially bloat the copy-paste gadget with functionality.

**Comment by MichaelHillcox** [comment] 2020-06-24 08:19
So this has actually been planned for a long time, I wanted to make a site to house all of these builds but I've not had the time. Once the site matured with a good majority of builds it would have been linked to an in-game block which people could load up. I can keep this open as it's basically locking this idea down in an offical manner but I still don't know when I'll have the time to work on the site. Soon hopefully as I've had the designs done for about 3 months now.

**Comment by Kegulf** [comment] 2020-06-24 08:44
Is there an existing site?
What is the site built with?
Anything I can help with, I'm a React dev, but I'm pretty versatile 😊

**Comment by MichaelHillcox** [comment] 2020-06-24 10:11
No existing site, currently planned to use something like Laravel to power the backend with vue for the frontend but I use both vue and react so either work in my eyes. The backend needs the work more than the frontend does but if you we're willing to work under a MIT license and you'd be willing to show me some of your work 😄 Laravel is also pretty optional for the backend, I work with a large volume of tech stacks so I'm pretty flexabile with how it's made. 

My plan would be to: 
- Import all builds from the 9x9 Reddit hopefully working with the guys over there to work out some intergration with them
- Build a backend with a frontend to fit my designs. It's a pretty simple system but needs to be built pretty robust for it's purpose, moderation, approvals, notifications, comments, reactions, template parsing to show resource requirements etc. In the fututre I'd like to be able to link to mod packs from curse etc too.
- Keep an eye on it's traction and useage and if people use it the way I intend for it to be used to then implement a way inside a block in the game to pull these templates in a searchable way which would automatically filter out ones that are the wrong game version, mod version, etc.

**Comment by MichaelHillcox** [comment] 2020-10-24 12:49
To keep things tidy, we now have master list of feature requests, we thank you for your suggestion and we will use this issue for future reference. Closing in preference for https://github.com/Direwolf20-MC/BuildingGadgets/issues/534

**Closed by MichaelHillcox** 2020-10-24 12:49 UTC
Labels: question
