### ISSUE TITLE
gadgets causing spam in the console

### ISSUE THREAD

**Issue by Basedgod199** [Direwolf20-MC/BuildingGadgets#324] opened 2019-06-30 14:15 UTC
forge-14.23.5.2838

BuildingGadgets-2.6.8

Bind a gadget to an inventory (in my case its a drawer filled with cobblestone) and then use the gadget

https://gyazo.com/039651436fbe1c0448067f1c3c740376

**Comment by MichaelHillcox** [comment] 2019-06-30 14:16
Did you press f to pay respects? Joking, let me take a look 👍

**Comment by MajorTuvok** [comment] 2019-06-30 14:20
We had this issue already, and it wans't our fault... Moment

**Comment by MajorTuvok** [comment] 2019-06-30 14:21
See #285

**Comment by MajorTuvok** [comment] 2019-06-30 14:27
Is the log you showed from the Server console or the log File? And could you share a larger portion of the log please, so that we can see what was happening before...

**Comment by Basedgod199** [comment] 2019-06-30 14:29
The screenshot is from the server console.
This is from the latest file: https://pastebin.com/YcXUHzTa

**Comment by MajorTuvok** [comment] 2019-06-30 14:40
So this is a different issue, but we still don't write an ffffff log entry...
In fact we don't write a single Log entry in GadgetUtils...

**Comment by Basedgod199** [comment] 2019-06-30 15:05
so loading up a test world with building gadgets and the thermal suite, it still happens.
so i tried removing all the thermal mods and change the gadgets to use durability instead of rf (so that they could be tested without needing other mods to charge them) and it still happens.
Here is a log from that test world: https://pastebin.com/XKxZ2Nn7

**Comment by MajorTuvok** [comment] 2019-06-30 15:12
Sorry but we still don't write a Log entry, I went through the code. I have to admit, thatI'm very curious as to why that happens, but there is no such Log entry unless I have misread code 3 times in a row...
A note: don't change RF/durability with a world that already existes! Minecraft doesn't like that.

**Comment by MajorTuvok** [comment] 2019-06-30 15:27
I cannot reproduce this issue, for refereence here is my [log](https://pastebin.com/mDzxx86b). I tested with the recommended Forge build (14.23.5.2768) and buildinggadgets full set of compatible mods.

**Comment by MajorTuvok** [comment] 2019-06-30 15:32
I can't test easily your Forge version, as cyclic keeps failing with that... Yould you try out Forge's recommended build and see what happens, if you enter **a new world**.

**Comment by Basedgod199** [comment] 2019-06-30 15:46
Still happens. Log: https://pastebin.com/rdavBQnH
Interesting how it doesn't happen for you with a list of mods and yet it happens to me with only building gadgets installed.

**Comment by MajorTuvok** [comment] 2019-06-30 16:03
That's really weird... :(

**Comment by MichaelHillcox** [comment] 2019-07-02 16:42
@Basedgod199 As this can't be reproduced I'm going to go ahead and close it. I would recommend you start up a completely new instance with just building gadgets and see if it continues to happen. If it doesn't then start to add more mods and keep an eye on your logs. It could be a different mod causing it. 

The most important thing to note here is that the log entry is "STDOUT" and we only have a few `STDOUT` related lines of code and none of them originate from the GadgetUtils file.

**Comment by Trinsdar** [comment] 2019-12-19 16:55
This is what's causing the issue: 
https://github.com/Direwolf20-MC/BuildingGadgets/blob/1.12.x/src/main/java/com/direwolf20/buildinggadgets/common/items/capability/ItemEnergyForge.java#L36

**Comment by MichaelHillcox** [comment] 2019-12-19 16:58
That isn't wants causing the issue as I don't think that code has been released. If it has then I'll be sure to edit it and re-release it as that's generic debugging code.

**Comment by MajorTuvok** [comment] 2019-12-19 16:58
No it is not, please read the issue first. I agree though that this is a log spam

**Comment by Trinsdar** [comment] 2019-12-19 17:10
Ok i did read the issue, that's in reference to a different but similar log spam on the atm3 expert official server: `[com.direwilf20.buildinggadgets.common.items.capability.ItemEnergyForge:extractEnergy:36]: EXTRACT` sorry for not clarifying

**Comment by MichaelHillcox** [comment] 2019-12-19 17:11
Looks like I did release that code. Seems like you've got something trying to use the gadget as a battery. I'll release a patch for it soon.

**Comment by MajorTuvok** [comment] 2019-12-19 17:12
Could you please open a new issue, with the standard data, instead of appending to this?
I'm sure @MichaelHillcox will release a fix soon if it is what we think it is, but we would like to have a new issue a) for clarity and b) for future reference+record

**Comment by Trinsdar** [comment] 2019-12-19 17:12
Ok

**Comment by MajorTuvok** [comment] 2019-12-19 17:13
We kind of answer at the same time, don't we? XD

**Comment by Trinsdar** [comment] 2019-12-19 17:31
anyways for this issue I think I found it: https://github.com/Direwolf20-MC/BuildingGadgets/blob/1.12.x-new/src/main/java/com/direwolf20/buildinggadgets/common/tools/GadgetUtils.java#L370

**Comment by MajorTuvok** [comment] 2019-12-19 18:15
Wow, really phyl

**Comment by MichaelHillcox** [comment] 2020-02-19 16:23
This doesn't affect versions after 2.7.x from what I can tell.

**Closed by MichaelHillcox** 2020-02-19 16:23 UTC
Labels: 1.12, unable to reproduce, unresolved
