### ISSUE TITLE
Uncentered settings

### ISSUE THREAD

**Issue by niklas2233** [Direwolf20-MC/BuildingGadgets#286] opened 2019-04-17 12:55 UTC
* Forge version: 14.23.5.2781
* Building Gadgets version: 2.6.8
* How to reproduce the issue
Change GUI Scale to large with high resolution (im using 2560x1440)
* A screenshot, if applicable
![2019-04-17_14 50 15](https://user-images.githubusercontent.com/33903786/56289249-cac0ee00-6120-11e9-9806-509f53155576.png)

**Comment by MajorTuvok** [comment] 2019-04-17 15:10
Duplicate of #206

**Closed** 2019-04-17 15:11 UTC
Labels: bug, duplicate
