### ISSUE TITLE
Better builders wand

### ISSUE THREAD

**Issue by zymex22** [Direwolf20-MC/BuildingGadgets#269] opened 2019-03-19 15:53 UTC
Hello! =) 
really love your new mod bring so much new building options to the game, i just miss one thing.
the option from BetterBuildingWand mod. 

i really miss the way to extend walls (same material) up when i have build a foundation of a house and want it up or to make floors 1 higher.

BetterBuildingWand in it self are a very nice mod, but have one biig drawback compared to yours, it have no undo button.
last couple of days i have failed and raised the dirt/grass in my world a few time, and its a pain to lower it again manually when its what 2-4k on the diamond one blocks? xD

would be very nice to have it all in "one" mod and your just have so many more features in it that i rather only use yours then BetterBuildingWand or NotEnoughWands
also i dont wanna use NEW because i have no need for other then the builders wand :P

**Comment by MajorTuvok** [comment] 2019-03-19 17:18
I'm not sure whether this would be implemented. In a first instance Dire closed #47, though I guess that might have been because it would have been too much effort in his opinion. As soon as #263 merged in this might be reconsidered though...?

**Comment by Phylogeny** [comment] 2019-03-19 21:50
Duplicate of #87. Implemented in v2.6.2 as `Surface Mode`

**Closed** 2019-03-19 21:53 UTC
Labels: duplicate, enhancement
