### ISSUE TITLE
copy-past duplication bug

### ISSUE THREAD

**Issue by Catumbik** [Direwolf20-MC/BuildingGadgets#352] opened 2019-08-27 01:26 UTC
Forge- 14.23.5.2821
* Building Gadgets version 2.7.3
It seems to be only  Biomes' o Plenty mod blocks I have tried several with the duplication result
![2019-08-26_20 16 50](https://user-images.githubusercontent.com/54562315/63733792-64bb4480-c83f-11e9-9876-0000e13cc3cb.png)
![2019-08-26_20 16 53](https://user-images.githubusercontent.com/54562315/63733793-6553db00-c83f-11e9-910d-4d3572d7eb0e.png)
![2019-08-26_20 16 59](https://user-images.githubusercontent.com/54562315/63733794-6553db00-c83f-11e9-961c-8022ea61460f.png)

**Comment by MajorTuvok** [comment] 2019-08-27 06:03
Thanks for the report...
What's the biomes O Plenty version you tested this with?

**Comment by MichaelHillcox** [comment] 2019-08-27 09:49
We've seen this before but basically just closed the issue as the dupe block you get is worthless. It's something to do with how pick block or silk touch methods see the block and we get two blocks out of it as when you break the block normally it gives back 2 things. Unfortunately we don't handle the second block like a truly unique block and just give back some odd version of it.

**Comment by MichaelHillcox** [comment] 2019-08-27 09:50
#225

**Comment by MajorTuvok** [comment] 2019-08-27 09:51
So it's a Duplicate of #225...

**Closed by MajorTuvok** 2019-08-27 09:51 UTC
Labels: 1.12, bug, incompatibility

**Comment by MajorTuvok** [comment] 2019-08-27 09:53
Duplicate of #225
