### ISSUE TITLE
Allow drawing items from player storage

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Direwolf20-MC/BuildingGadgets#188] opened 2019-01-14 07:40 UTC
https://github.com/MrRiegel/PlayerStorage

I am not sure how you would do it but it would be nice if you @Direwolf20-MC and @MrRiegel could work something out that would be awesome! Truly you guys are modding gods.

**Comment by Phylogeny** [comment] 2019-01-14 08:41
This is either a bug in Player Storage or in Lime Lib, on which it relies. The tooltips for all items in the player storage GUI are being rendered with empty stacks. You'll find that `getStack` in `RenderTooltipEvent.PostText` returns an empty one for both vanilla and modded items -- for every item in the GUI, in fact.

Please report this bug on one or both of the repos for those mods.

**Comment by P3rf3ctXZer0** [comment] 2019-01-14 12:38
Um - what?! XD I am confused maybe you should break it down for them @Phylogeny

**Comment by Phylogeny** [comment] 2019-01-14 13:02
No problem.

For each extended storage slot, `mrriegel.playerstorage.gui.GuiExI#drawscreen` [is calling](https://github.com/MrRiegel/PlayerStorage/blob/1.12/src/main/java/mrriegel/playerstorage/gui/GuiExI.java#L223) `mrriegel.limelib.gui.element.AbstractSlot#drawTooltip`, which is [in-turn calling](https://github.com/MrRiegel/LimeLib/blob/12cad11926a63424dcdc7b86b57d158b78dad097/src/main/java/mrriegel/limelib/gui/element/AbstractSlot.java#L58-L59) `GuiUtils#preItemToolTip` to set the cashed stack, then `GuiUtils#drawHoveringText` to draw it. It appears the problem is that an empty stack is being passed to `GuiUtils#preItemToolTip`, rather than the actual stack that the tooltip is being rendered for. Since the stack's ITemplate item is [used to retrieve the items to be rendered in `RenderTooltipEvent.PostText`](https://github.com/Direwolf20-MC/BuildingGadgets/blob/master/src/main/java/com/direwolf20/buildinggadgets/client/events/EventTooltip.java#L99-L101), nothing is found to render.

**Comment by Direwolf20-MC** [comment] 2019-01-23 01:30
So this isn't on my end, right @Phylogeny -- closing :)

**Closed by Direwolf20-MC** 2019-01-23 01:30 UTC

**Comment by Phylogeny** [comment] 2019-01-23 08:37
That's right, it's not at all on your end. :)
