### ISSUE TITLE
[1.12.2] Crash when Selecting Futurepack Plasma Lamp with Exchanging Gadget

### ISSUE THREAD

**Issue by AlphaTrooperY** [Direwolf20-MC/BuildingGadgets#354] opened 2019-08-28 20:18 UTC
Details/Background: I was on Menelaus, a planet added by the mod Futurepack, looking for a second Bedrock Rift, and wanted some lights. I had spare Plasma Lamps from salvaged small dungeons, where the metal was used to make my spacecraft. I wondered if I could exchange the stone for a plasma lamp, and it crashed. So here I am reporting the crash.

Minecraft Version: 1.12.2
Forge Version: 14.23.5.2838
Building Gadgets Version: 2.7.2
Futurepack Version: 26.4.82
Crash Report: https://pastebin.com/HKnwjxWS
How To Reproduce:
	1. Get the Exchanging Gadget, a Futurepack Plasma Lamp of any color, and some sort of power source for the Exchanging Gadget.
	2. Place the Plasma Lamp in the world.
	3. Select the Plasma Lamp with the Exchanging Gadget.
	4. Crash.

Thank you for the response.

**Comment by MajorTuvok** [comment] 2019-08-28 21:20
This is an issue of Future Pack for which I reported a very similar one to galactic raft a while ago

**Comment by MajorTuvok** [comment] 2019-08-28 21:25
I'll check tomorrow...

**Comment by AlphaTrooperY** [comment] 2019-08-29 14:58
If you think it's Futurepack's fault, I will post it on their bug tracker too.

**Comment by MajorTuvok** [comment] 2019-08-29 15:11
The Problem is I can only find [this](https://github.com/mcenderdragon/Futurepack-API) which would imply that it's not open source, so I cannot check what they are actually doing and show them the error. 
I am pretty sure that they are trying to get the State from the BlockPos, which obviously won't work because the Block isn't placed yet - instead they should be using the BlockState passed in.

**Comment by MajorTuvok** [comment] 2019-09-01 17:54
Compare #330 - I think they have the same underlying Problem. I'm pretty sure that this is Futurepack's fault - closing unless proven otherwise

**Closed by MajorTuvok** 2019-09-01 17:54 UTC
Labels: 1.12, bug, incompatibility, third party issue
