### ISSUE TITLE
Forge .73 crashes due to updates (breaking changes) to IConditionSerializer

### ISSUE THREAD

**Issue by Wissi** [Direwolf20-MC/BuildingGadgets#355] opened 2019-08-29 09:01 UTC
Awesome mod, loving it so much.
We are getting this crash on client and on server, full crash logs client [here](https://gist.github.com/Wissi/caa86f7525e502ecb6c6da797deee0cb) and server [here](https://gist.github.com/Wissi/29b9d331b308dfacc9513749af8ca64a).

Using:
* forge-1.14.4-28.0.73
* buildinggadgets-3.0.2.jar
* buildinggadgets-3.0.4.jar

**Comment by MajorTuvok** [comment] 2019-08-29 09:03
This is caused by the Forge update... If you go back to Forge .55 for which 3.0.4-hotfix was compiled it will work again.

**Comment by MichaelHillcox** [comment] 2019-08-29 09:05
I'll bump our version and release a minor today but for now just bump your forge down and make sure you're on the latest alpha

**Comment by Wissi** [comment] 2019-08-29 09:06
Awesome work. 
Yes it works perfectly fine with Forge .55
Still wanted to report.
Thanks.

**Comment by MichaelHillcox** [comment] 2019-08-29 09:06
I'll update you when I release the new minor version :)

**Comment by LlubNek** [comment] 2019-08-30 22:51
getting the same thing on forge .74 and .75

.75:
[crash-2019-08-30_18.13.00-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/3561771/crash-2019-08-30_18.13.00-client.txt)
[2019-08-30-2.log.gz](https://github.com/Direwolf20-MC/BuildingGadgets/files/3561774/2019-08-30-2.log.gz)

.74:
[crash-2019-08-30_18.15.52-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/3561772/crash-2019-08-30_18.15.52-client.txt)
[latest.log](https://github.com/Direwolf20-MC/BuildingGadgets/files/3561773/latest.log)

**Comment by MajorTuvok** [comment] 2019-08-31 05:26
Of course you are?!?

**Comment by MajorTuvok** [comment] 2019-08-31 14:32
Fixed in 38d3d99 - awaiting release

**Closed by MajorTuvok** 2019-08-31 14:32 UTC
Labels: 1.14, incompatibility

**Comment by MajorTuvok** [comment] 2019-09-01 05:58
Fixed in 3.0.5 (which Mike released yesterday)
