### ISSUE TITLE
New gadget: cut and replace gadget!

### ISSUE THREAD

**Issue by aleZZ1994** [Direwolf20-MC/BuildingGadgets#442] opened 2020-02-23 19:53 UTC
Hello :) I'm literally happy with this mod because it's very easy to use and very helpful but the only flaw is that there is no possibility to cut and move a selected part. I think It's very helpful so I hope to be implemented soon. Thank you for the attention. Bye :)

**Comment by MajorTuvok** [comment] 2020-02-23 19:54
We already planned that last year, and some time ago someone else requested this - we just did not get to it...
Sorry...

**Comment by MajorTuvok** [comment] 2020-02-23 19:56
Duplicate of #381

**Closed** 2020-02-23 19:56 UTC
