### ISSUE TITLE
Crash when attempting to select a shulker box

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#368] opened 2019-09-07 08:05 UTC
Pretty straight forward: A use on discord reported that 
> My game crashed after shift clicking with exchange on a shulker box

I think we found our first TE-issue

**Comment by HeuristicBishop** [comment] 2020-05-27 23:10
I could not reproduce this crash.

Minecraft: 1.14.4
Forge: 28.1.79
Building Gadgets: 3.1.1b

If you can repro this bug let me know how. I'll take another look.

**Comment by MichaelHillcox** [comment] 2020-07-16 17:04
Can not reproduce in 3.1.1b with an updated forge version. Closing

**Closed by MichaelHillcox** 2020-07-16 17:04 UTC
Labels: 1.14, bug
