### ISSUE TITLE
Crash with exchanger and Natura Eucalyptus log

### ISSUE THREAD

**Issue by choekstr** [Direwolf20-MC/BuildingGadgets#296] opened 2019-05-04 04:54 UTC
**IMPORTANT:** Before continuing, please ensure that Building Gadgets (and any other mods involved) is updated to the latest available version
----------------------------------------------------------------------------
After deleting this template, please provide the following information:
* Forge version: forge-14.23.5.2816
* Building Gadgets version: 2.6.8
* *If the issue is a crash*; An external link to the crash report: [https://pastebin.com/NBTDeWj7](https://pastebin.com/NBTDeWj7)
* How to reproduce the issue: Shift right click on a Eucalyptus log, crash.  load back in, select exchanging gadget, crash.
* A screenshot, if applicable

**Comment by choekstr** [comment] 2019-05-04 17:55
Hmm, seems to have been a COFH Holding IV enchant on a satchel causing all kinds of issues and presented as a building gadget issue.

**Comment by MajorTuvok** [comment] 2019-05-04 17:59
Correct: Though this is not cofh's fault either. There's some mod at work, we're unable to find out about.
This will hopefully be resolved, when we rewrite the InventoryHelper code.

**Comment by MajorTuvok** [comment] 2019-05-04 18:00
Duplicate of #280

**Closed by MajorTuvok** 2019-05-04 18:00 UTC
Labels: 1.12, duplicate, incompatibility, unable to reproduce, unresolved

**Comment by MichaelHillcox** [comment] 2019-05-07 22:01
Please find attached a link to a possible mod that may have been causing this crash
#280 (comment)

**Comment by choekstr** [comment] 2019-05-08 00:52
Seems like this fits my situation.  I commented on that thread...
