### ISSUE TITLE
Structure preview stays

### ISSUE THREAD

**Issue by stevojhall** [Direwolf20-MC/BuildingGadgets#178] opened 2019-01-09 02:43 UTC
Is there any way to keep the structure preview active until a button is pressed. A mod called Prefab does this really well and allows players to clear out an area around your structure easier. 

This would also allow players  to build around a structure that they are not ready to build yet.

**Comment by MichaelHillcox** [comment] 2019-01-09 12:03
I'll assume you mean having it stay even when the tool isn't in your hand?

**Comment by Direwolf20-MC** [comment] 2019-01-09 20:41
Hrm, I could probably make it so that it stays if anchored and on your hotbar...I'll consider it :)

**Comment by MajorTuvok** [comment] 2019-01-09 21:15
Maybe allow the user to toggle 'static anchoring' on/off? (Config gui option (client side only)...?)

**Comment by stevojhall** [comment] 2019-01-10 08:30
@MichaelHillcox yes something like that. Direwolf20-MC knows what i mean which is good. Hopefully will get added although its Dire's mod so final decision is his.

@MajorTuvok i didn't think of a toggle, that's a great idea if it gets added

**Comment by KonKeyHD** [comment] 2019-01-27 01:44
Having the tool in the offhand (press: F) will keep the ghost blocks visible.

**Comment by MichaelHillcox** [comment] 2019-05-28 09:57
As keeping the tools in the offhand already allows you to do this I'm going to go ahead as say this already exists and works as intended 👍 if you have any reason to keep this open then please let me know and reopen the issue.

**Comment by MajorTuvok** [comment] 2019-05-28 15:03
I'd like to keep it open anyway, as showing it independant of the Gadget would be a nice feature in my opinion.
Implementation suggestion: Instead of directly rendering whatever the Gadget has in the Hand, register and unregister the blocks to render from some kind of central preview renderer.

**Comment by MichaelHillcox** [comment] 2020-10-24 12:51
To keep things tidy, we now have master list of feature requests, we thank you for your suggestion and we will use this issue for future reference. Closing in preference for https://github.com/Direwolf20-MC/BuildingGadgets/issues/534

**Closed by MichaelHillcox** 2020-10-24 12:51 UTC
Labels: enhancement
