### ISSUE TITLE
Crash when placing water block next to Construction paste with bucket

### ISSUE THREAD

**Issue by hibikutek** [Direwolf20-MC/BuildingGadgets#532] opened 2020-10-19 16:15 UTC
* Forge version 32.0.108
* Building Gadgets version 3.5.1
* Crashlog [here](https://pastebin.com/gv7Tg8zs)
* How to reproduce the issue:
Place Construction Powder in world, rightclick side of powder block with water bucket.

**Comment by MichaelHillcox** [comment] 2020-10-19 16:17
Thanks, I’ll look into it

**Comment by hibikutek** [comment] 2020-10-19 16:23
Oof, logged back in and tried placing the powder from inventory next to water source block, got another [crash ](https://pastebin.com/nVePrsi4)

Oddly enough, when logging back in, it does just fine.  By the way, this is on a dedicated server in case it's one of the ol' sided errors.

**Comment by MichaelHillcox** [comment] 2020-10-30 18:24
Can not reproduce, looks like you're on MC 1.16.1, you should update as I'm not having this in 1.16.3 on the latest version of the mod. Closing for now.

**Closed by MichaelHillcox** 2020-10-30 18:24 UTC
Labels: 1.16, bug
