### ISSUE TITLE
Replacing or removing stone fails and makes a laugh sound.

### ISSUE THREAD

**Issue by Malus-Lupo** [Direwolf20-MC/BuildingGadgets#232] opened 2019-02-11 15:26 UTC
Forge 14.23.5.2808
Building Gadgets 2.6.1
No crash just on my server when I try to replace or remove stone with ether gadget it fails and makes a really odd laugh sound. It removes the dirt around it and makes no sound if there is no stone to be removed, ie no sound if it removes every block asked to. Tested and working in a single player world.

**Comment by Phylogeny** [comment] 2019-02-11 15:36
All gadgets respect blocks protections added by other mods/plugins. Nothing you're describing sounds like a bug, but like the stone is protected by a mod or a server plugin. The laughing should be a red flag.

**Comment by Malus-Lupo** [comment] 2019-02-11 18:05
Well you might have closed it early, as I have no mod or server plug in that should be protecting or allows players to protect blocks, And I am the admin of the server so even if there was I would have the permissions required to remove said blocks.

**Comment by Phylogeny** [comment] 2019-02-11 18:11
The description is inconsistent with a bug, and is consistent with some form of protection. And there is no grantee that a protection mod/plugin respects admin status.

**Comment by Malus-Lupo** [comment] 2019-02-11 18:42
I am the only person who admins the server, uploaded every file my self, there is no protection mod. Even if there was, if a protection mod was protecting the stone, why would it not be protecting the dirt and grass in the same chunks?

**Comment by Phylogeny** [comment] 2019-02-11 18:48
And why would laughing sounds play? Why does anyone add the odd things they do into mods? In any case, then the next step is removing/adding mods until the mod with the incompatibility is identified. There is nothing yet that can be done on this end.

**Comment by Malus-Lupo** [comment] 2019-02-11 19:16
The mod would be Tinkers Survival, but I added Building Gadgets to the "List of mods that tools will always work for" and the tools its self to " List of individual tools that will always work. "  in Tinkers Survival config already. And it did not allow the tools to work.

**Comment by MajorTuvok** [comment] 2019-02-11 19:18
Still the laugh sounds makes it pretty likely, that this is not caused by BuildingGadgets...

**Comment by Malus-Lupo** [comment] 2019-02-11 19:38
All the laugh means is that the failing to break a block causes the laugh to happen, it happens when you use a empty hand or the wrong tool to break the block as well. But how that proves the error is not in Building Gadgets I have no clue. All that Id say it proves is that for some reason Tinkers Survival sees building gadget tools as not real tools, that could be caused by a error in ether mod. I made a bug report in the Tinkers Survival Gethub as well.

**Comment by Phylogeny** [comment] 2019-02-11 19:39
Do you see this in the log: "TOOLS_WHITELIST item [name] has an incorrect format."?

**Comment by Malus-Lupo** [comment] 2019-02-11 19:46
Yes I do see that.

**Comment by Malus-Lupo** [comment] 2019-02-11 19:48
I added buildinggadgets to the first list, the list of mods names, adding bloodmagic allowed Blood Magics tools to work, and the second list I added buildinggadgets:destructiontool.

**Comment by Phylogeny** [comment] 2019-02-11 19:50
It says right there that the format is "tooltype-modid:item". That's not what you input.
The valid tooltypes are: https://github.com/wendall911/TinkerSurvival/blob/a4f4e0a78d913b9ddc90f258a93f3f78bf40cf9a/src/main/java/tinkersurvival/util/ItemUse.java#L27-L37

**Comment by Malus-Lupo** [comment] 2019-02-11 19:58
Added the pickaxe- and reloaded.  The first config list renders the second config list redundant. So it did nothing, Tho the log no longer shows "TOOLS_WHITELIST item [name] has an incorrect format."?.

**Comment by Phylogeny** [comment] 2019-02-11 21:19
Yes, this definitively has to do with Tinkers Survival not recognizing the gadgets. However, it is not a bug on either end. I'll re-open this, and see if something can be done on this end to integrate with that mod, but it may not be feasible. I'll look into it further later.

And you can close the issue in Tinkers Survival, since they are not doing anything wrong, and there is nothing they can do about this.

**Comment by Malus-Lupo** [comment] 2019-02-11 21:24
Thank you.

**Comment by Malus-Lupo** [comment] 2019-03-14 17:04
If any one else finds this because they use these two mods, I found a work around, if you hold the building gadget in your off hand and a pick in your main hand and the building gadget might need to be in both config lists as explained above it seems to work.

**Comment by MajorTuvok** [comment] 2019-09-01 17:44
As there's a work-around and no one else seems to have noticed it, I'm going to close this,

**Closed by MajorTuvok** 2019-09-01 17:44 UTC
Labels: incompatibility
