### ISSUE TITLE
[1.14.4] Sidedness issue when run on a dedicated server. Attempted to load class net/minecraft/client/resources/I18

### ISSUE THREAD

**Issue by ProsperCraft** [Direwolf20-MC/BuildingGadgets#339] opened 2019-08-06 22:16 UTC
When players use building gadgets on the server, it doesn't crash the server but it has this stacktrace in console-

https://gist.github.com/ProsperCraft/e9ca3f07236d6c2c68299b5526fcd6bb

**Comment by MajorTuvok** [comment] 2019-08-07 06:04
This is missing descriptions...
Version:? 
Other mods? 
But this isn't necessary in this case I guess, cause the stacktrace already shows where ir comes from..

**Comment by ProsperCraft** [comment] 2019-08-07 15:13
Right, sidedness issues are very clear.  The Minecraft version is in the topic.

**Comment by MichaelHillcox** [comment] 2019-08-07 15:15
I'm closing this until actual detail is supplied. 

Required:
- Mod version 
- Forge version 
- Full crash log
- Other mods if applicable. 

Our template is to help us fix the issue as fast as possible. If you can't provide this information we won't waste our time trying to resolve the issue with limited information.

**Comment by ProsperCraft** [comment] 2019-08-07 15:31
Right, well 95% of all of the mods updating to 1.14.4 have had issues with sidedness because it changed in 1.14 I thought building gadgets was in the clear and was impressed until players started using it then saw this in the server console, the player reports it still works, and surprisingly it doesn't crash when calling client code on the dedicated server.  

If you check my github history you will see this problem has been reported and resolved many many many times.

Steps to reproduce- 
Set up a dedicated server
install building gadgets
connect to dedicated server
use the device, watch console.

buildinggadgets-3.0.0
forge-1.14.4-28.0.40
There is no crash log as the server did no crash.

Modlist- https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk
144 mods

server log- 
[2019-08-06-3.log](https://github.com/Direwolf20-MC/BuildingGadgets/files/3477746/2019-08-06-3.log)

**Comment by MajorTuvok** [comment] 2019-08-07 15:33
This is not an update issue - you can propably find this one in 1.12.2 too. It was caused by rewriting the mode System and then the Person who rewrote it never thought of testing with a dedicated Server -_- (looking at someone hn)

**Comment by MajorTuvok** [comment] 2019-08-07 15:36
Looking at 1.12.2 I can't seem to find that TextComponent?!?

**Comment by MajorTuvok** [comment] 2019-08-07 16:03
So @MichaelHillcox just found the commit which fixed it in 1.12 (https://github.com/Direwolf20-MC/BuildingGadgets/commit/6fcc11368d83608c030ed8c8a3e8aa17ceab7ef6)...
This looks like it was straight up not applied for the 1.14 branch sorry @ProsperCraft

**Comment by MichaelHillcox** [comment] 2019-08-07 16:46
Should be fixed as of b609b6f2890f2a91fd14426d6910c4742b0b846a

**Closed by MichaelHillcox** 2019-08-07 16:46 UTC
Labels: 1.14, bug
