### ISSUE TITLE
Crash with (Holding IV) CoFH satchel in inventory

### ISSUE THREAD

**Issue by Zerotiger** [Direwolf20-MC/BuildingGadgets#301] opened 2019-05-07 12:55 UTC
I've been using the diamond satchel with 36 slots for a while without any problems. The problem started when I crafted a 45 slot "Satchel (Resonant)" and also enchanted it with Holding IV to have 81 slots.

As soon as I had the satchel in my inventory the Copy-Paste gadget tooltip render causes crash. The exchange gadget causes crash when attempting to render the block overlay (while in hand).

Minecraft: 1.12.2
Forge version: 14.23.5.2836
Building Gadgets version: 2.6.8
CoFH core: 4.6.2.25
Thermal Foundation: 2.6.2.26
Thermal Expansion: 5.5.3.41

Steps:
1. Have a "Satchel (Resonant)" in inventory (I think it has to be enchanted with Holding to cause the issue)
2. Have a "Copy-Paste Gadget" in your inventory and hover the item with your mouse. (I've tried clearing the gadget and didn't seem to make a difference.
3. Crash

Alternative step 2.
Have an "Exchange gadget" in your toolbar and hold it in your hand. (Mine was set to use a block I didn't have in my inventory, and "Surface" with range 1)

The satchel:
![image](https://user-images.githubusercontent.com/4203804/57300005-35d56300-70d6-11e9-9a37-78f0870baa00.png)

Two crash logs:
Tooltip: https://paste.dimdev.org/ohoqovuhec.mccrash
Block overlay: https://paste.dimdev.org/refimojixa.mccrash

I just noticed that there are other similar report, but I hope this information might still be useful for tracking down the bug. I was not sure where to report at first, but as the issues are clearly related to the use of the building gadgets, I figured here would be best.

**Comment by MajorTuvok** [comment] 2019-05-07 14:02
Duplicate of #280

**Closed by MajorTuvok** 2019-05-07 14:02 UTC
Labels: 1.12, bug, duplicate, incompatibility, unresolved

**Comment by MichaelHillcox** [comment] 2019-05-07 22:01
Please find attached a link to a possible mod that may have been causing this crash
#280 (comment)

**Comment by Zerotiger** [comment] 2019-05-07 22:01
Thank you, that's my comment :)

**Comment by MichaelHillcox** [comment] 2019-05-07 22:02
(I've posted it on all linked crash reports as we've had a few, thanks again for finding out what mod was causing this)
