### ISSUE TITLE
Copy/Paste Across World 1.16.4

### ISSUE THREAD

**Issue by GamingFanatics** [Direwolf20-MC/BuildingGadgets#551] opened 2020-11-25 03:29 UTC
In version 3.7.2 (Latest) gives an error of "Paste Failed, MC Version (1.12.x) is not supported. Please use only templates that were buid for the current version (1.16.4)." However, it was copied from another world in the same instance without even closing the game. That being 1.16.4.

**Comment by hvdklauw** [comment] 2020-11-25 06:48
Thanks for the report, if you have the file for me that would really help.

I'll have a look at it

**Comment by hvdklauw** [comment] 2020-11-25 10:14
Yeah, I'll need more information, it works for me, having the template itself would really help but also blocks used etc.

**Comment by MichaelHillcox** [comment] 2020-11-25 10:54
The odd thing is that error should only ever show if you read code that is able to be parsed by the nbt string reader which should only work on 1.12. This was an intentional move to try and make it clear on what versions work on what mod versions

https://github.com/Direwolf20-MC/BuildingGadgets/blob/master/src/main/java/com/direwolf20/buildinggadgets/client/screen/TemplateManagerGUI.java#L622

**Comment by GamingFanatics** [comment] 2020-11-25 13:37
Actually, I did some tests, it was only because the world I was using to build stuff in was created in 1.12, however, I have just been copying it every version so I do not know if that's suppose to be how it is if the world was created in a past version, or what. But as far as I can tell that was my issue.

**Comment by GamingFanatics** [comment] 2020-11-25 13:45
Nevermind, I tried it in my survival world and it still gave me the error. Here is a Pastebin for the copy. https://pastebin.com/rtmaXPem

**Comment by hvdklauw** [comment] 2020-11-25 14:07
Thank you, looking at the file everything seems to be correct , I'll do debugging tonight

**Comment by MichaelHillcox** [comment] 2020-11-25 14:47
Okay, something is wrong with the error but I actually know what the root cause of this issue is, I forgot to update the template header java class to be 1.16.4.

**Comment by MuteTiefling** [comment] 2020-12-01 06:51
I was running into this tonight and was about to open a ticket when I found this. Out of curiosity, I tried updating the headers in my exported templates and they still were not importing. 

[Basic Fission Reactor.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/5620718/Basic.Fission.Reactor.txt)

Not sure if it's just the header change or if something will change on the 'read' end when this is pushed?

**Comment by hvdklauw** [comment] 2020-12-01 06:56
The problem is part the header not being updated and part the copy part not copying correctly.

I'll have a look today at the code, there where issues with engineer's decor catwalks too.

**Comment by MuteTiefling** [comment] 2020-12-01 07:21
Per our quick chat on discord, here are the rest of the templates in case it helps: https://gist.github.com/MuteTiefling/5a8b425273a1008c0163b786b8780ba4

**Comment by hvdklauw** [comment] 2020-12-01 08:09
Tested them, those all work with the fix I have ready, they load, paste and form a multiblock!

**Comment by hvdklauw** [comment] 2020-12-01 08:29
fixed with #554

**Closed** 2020-12-20 16:48 UTC
Labels: 1.16, bug, oversight, pending release
