### ISSUE TITLE
Building Stairs downwards

### ISSUE THREAD

**Issue by Edwin-Baranov** [Direwolf20-MC/BuildingGadgets#601] opened 2021-02-02 04:56 UTC
When I found a ravine I wanted to go down into it using the stairs option in the building gadget however currently you can only build stairs up from the aimed block.

If you are pointing to a block above your head  the stairs will be built down towards you. This feature while still useful for getting to high locations without having to look at the ground and guess the range, does not achieve the ability to build down into a hole.

My suggestion is that when the building gadget is in stairs mode a button on the right appear to toggle between building up and building down (have a player icon with the stairs to indicate direction). When it down mode if your looking at any block side other than the bottom it will build down, if the angle of the head is facing upwards then the gadget is unable to build at all since you obviously cant build down facing up.

![Screenshot 2021-02-01 204137](https://user-images.githubusercontent.com/10283281/106553697-bc4aee80-64ce-11eb-8df0-922a9f663268.png)
![Screenshot 2021-02-01 204206](https://user-images.githubusercontent.com/10283281/106553699-be14b200-64ce-11eb-8bf3-8003537263ed.png)

**Comment by MajorTuvok** [comment] 2021-02-02 08:06
Almost a duplicate of #396 - not sure whether the toggle suggestion should be included into the master list...

**Comment by MichaelHillcox** [comment] 2023-02-26 18:17
Fixed for 1.18 + 1.19

**Closed by MichaelHillcox** 2023-02-26 18:17 UTC
Labels: enhancement, 1.16
