### ISSUE TITLE
[2.6 and 2.7, MC 1.12] Binding to Inventory (Applied Energistics) Bug?

### ISSUE THREAD

**Issue by tursi960** [Direwolf20-MC/BuildingGadgets#356] opened 2019-08-30 13:12 UTC
If you bind any of the gadgets to the ME System, very strong server lag occurs on placement of blocks.

I don't know if the implementation works by some kind of pull request and it's on Applied Energistic's end, but I just want to report this.

If any one has a solution that'd be great.

(Pack is E2E 1.66c (customized), this problem occured before any modlist changes were done)

**Comment by MajorTuvok** [comment] 2019-08-30 13:22
This is most likely caused by a very full me system, which requires iteration upon all the stacks if I'm not mistaken. I have no intention on doing anything about that for 1.12 though  - I guess @MichaelHillcox and Dire neither.

**Comment by tursi960** [comment] 2019-08-30 13:23
Would creating more ME Storage Space help?

**Comment by MajorTuvok** [comment] 2019-08-30 13:29
I don't know - That depends on how applied energistics handles that, thought I'd guess that more space would make it worse

**Comment by MajorTuvok** [comment] 2019-08-30 13:34
Therefore we have O(n*m) performance for building something with m being the amount of blocks to place and n being the amount of accessible stacks (player inv + bound inv.)

**Comment by MajorTuvok** [comment] 2019-08-30 13:38
Getting O(n+m) at the cost of O(m) memory whouldn't be so hard, but there are more important things at the moment

**Comment by tursi960** [comment] 2019-08-30 13:43
Haha, no problem! Would be great for the modpack community though as I think most people would consider most mods to be core mods.

I have some time on my hands right now, if you could point me in the right direction in 3 sentences, where would I begin to fix this for me privately? (ofc if bugfree publicly)

**Comment by MajorTuvok** [comment] 2019-08-30 15:23
What do you mean with that? If you are referring to PR this:
- you'd need to create some sort of mapping system from UniqueItem to the location where they can be found. That would then be created before placing blocks and used to retrieve them. 
- of course that'd need to happen for 1.14

**Comment by MichaelHillcox** [comment] 2019-08-30 16:18
From what I've read here it looks like the ME system is super full requiring us to iterate over each item in order to find and take those items. Would I be right in thinking that this is the bit causing the lag? If it is when I can look into it for you

**Comment by tursi960** [comment] 2019-08-30 17:03
@MichaelHillcox Yes. Probably. I'm pretty much endgame in this pack with like 3 ME Drives full of unique items. Does VirtualVM show me these processes? If it does, I could say for sure.

**Comment by MichaelHillcox** [comment] 2019-11-06 17:57
I can't reproduce this as your situation is surprising complex. I'm going to close the issue for now but it would be great if you could send me your world, the mod pack you're using any anything else that might be helpful. You can reach me at me@mikey.pro

**Closed by MichaelHillcox** 2019-11-06 17:57 UTC
Labels: 1.12, 1.14, performance
