### ISSUE TITLE
latest forge builds breaks mod 1.14.4

### ISSUE THREAD

**Issue by raziel23x** [Direwolf20-MC/BuildingGadgets#338] opened 2019-08-04 03:17 UTC
* Forge version 1.14.41.14.4-28.0.37
* Building Gadgets version 3.0.0
* *If the issue is a crash*; An external link to the crash report
https://pastebin.com/n4NiidyY
* How to reproduce the issue run latest version of forge 
* A screenshot, if applicable

**Comment by MajorTuvok** [comment] 2019-08-04 05:57
What's the BuildingGadget's version? And how did you manage to make the ColorHandlers null?!?

**Comment by raziel23x** [comment] 2019-08-04 13:58
right now there is only one version of building gadgets for minecraft 1.14.4

**Comment by MajorTuvok** [comment] 2019-08-04 14:07
That is correct, but I wanted to have it in here for future reference. Ok I'll do itmyswlf then.

**Comment by MajorTuvok** [comment] 2019-08-04 14:11
And could you maybe provide a description?!? [Sorry but I hate it, if people are unable to just type in information which takes them 10s but for those reading it at least a minute every time they look at the issue. There's a reason for deacriptions...]

**Comment by raziel23x** [comment] 2019-08-04 14:13
all i did was update to the latest versions of forge for 1.14.4

**Comment by MajorTuvok** [comment] 2019-08-04 14:14
Reading the linked crash report here the necessary info:
- Crash occurs on startup.

**Comment by MajorTuvok** [comment] 2019-08-04 14:18
Reading this through, this seems to be identical to #335

**Comment by MajorTuvok** [comment] 2019-08-04 14:25
Could you start removing mods (or re-adding) and trx to figure out whether this also doesn't happen for you on a regular basis?
I'm getting the impression that this is a Forge bug, caused by some kind of race condition

**Comment by raziel23x** [comment] 2019-08-04 15:28
as soon as i disable this mod modpack loads and seeing this is a alpha build and forge seems to break stuff every few builds it a issue with forge breaking the API because of changes done to forge

**Comment by MajorTuvok** [comment] 2019-08-04 17:03
@MichaelHillcox I just remembered that our Blocks are not set by the RegistryEvent, but instead applied by the ObjectHolder - which I'm very sure we are supposed to do. This would imply that it might be possible to fix this, by manually setting the value instead of relying upon ObjectHolder to fire as promised.

This would of course also imply that Forge in some situations (presumably race conditions at work) incorrectly applies ObjectHolders after the ColorHandlerEvent.

**Comment by MajorTuvok** [comment] 2019-08-04 17:05
@raziel23x using only buildinggadgets, what is the earliest Forge version, in which you can notice the crash?

**Comment by MajorTuvok** [comment] 2019-08-04 17:07
And if you are unable to reproduce with just buildinggadgets, how many mods do you need to be able to reproduce this, and which ones are they?

**Comment by raziel23x** [comment] 2019-08-04 17:20
I upgraded from 1.14.41.14.4-28.0.34

**Comment by MajorTuvok** [comment] 2019-08-04 17:30
Yeah, but what if you remove the other mods... We already had this issue and once torchmaster vanished all was fine - and after a Torchmaster update, that also worked again

**Comment by raziel23x** [comment] 2019-08-04 17:44
weird its now loading with no changes all i did was downgrade forge to 1.14.41.14.4-28.0.32 and then upgraded it to 1.14.41.14.4-28.0.40 and now it working just fine

**Comment by raziel23x** [comment] 2019-08-04 17:46
Chalk this up to being a issues with twitch launcher?

**Comment by MajorTuvok** [comment] 2019-08-04 18:06
So I just had a very intresting discussion with Lex... Apperently there seems to be something out of order with the ColorHandlerEvent or the ObjectHolder. 
In the meantime we can just ignore the ColorHandlerEvent and register in ClientSetup

**Comment by MajorTuvok** [comment] 2019-08-04 18:07
I don't know why it even it exists then, but not going to ask to much -_-

**Comment by MajorTuvok** [comment] 2019-08-04 18:38
This should be fixed now, according to the discussion on the Forge Discord. This is a workaround for a Forge bug though.

**Closed by MajorTuvok** 2019-08-04 18:38 UTC
Labels: 1.14
