### ISSUE TITLE
Building Gadget Causes Hanging

### ISSUE THREAD

**Issue by bobothehobo2** [Direwolf20-MC/BuildingGadgets#288] opened 2019-04-19 17:05 UTC
When using the building gadget it consistently hangs the entire game forcing a kill and restart.

Forge Version - 14.23.5.2781
Gadgets Verson - 2.6.8

See attached debug log
[debug-1.log](https://github.com/Direwolf20-MC/BuildingGadgets/files/3098790/debug-1.log)

**Comment by MajorTuvok** [comment] 2019-04-21 10:03
Duplicate of #287

**Comment by MajorTuvok** [comment] 2019-04-21 10:04
Only difference is that it's the exchanging Gadget there, but the same error. Let's combine the discussion over there,

**Closed by MajorTuvok** 2019-04-21 10:04 UTC
Labels: 1.12, bug, duplicate, incompatibility
