### ISSUE TITLE
Post Tile Detection handling (aka put it here)

### ISSUE THREAD

**Issue by generrosity** [Direwolf20-MC/BuildingGadgets#203] opened 2019-01-20 18:30 UTC
As I understand, the gadgets can detect tile entities as the blocks are being processed, and the template manager will invisibly drop tile entity blocks.

This means when pasted its sometimes not obvious if a tile entity is designed to be on top of an existing block. And we can't leave signs.

Would it be possibly to encode a "magenta terracotta ↓" block to be placed instead? This would clearly indicate a missing block and a simple usually unused block that would stick out. Potentially, the name and lore could match the block name and modid.

**Comment by MajorTuvok** [comment] 2019-01-21 20:12
We could maybe construct Constructionblocks in there (with the missing block model?) and set them to not drop anything...

**Comment by generrosity** [comment] 2019-01-22 22:02
Niiice - missing models from paste would be cool - I could imagine a gray 'clay'/'porcelain clay' statue appearing where something once was.

That would need to copy the model into the export tho - wouldn't that get quite big for complex models like BloodMagic's Hellfire Forge? I don't know if you have a max-clipboard limit you are working with.

If not, having models listed at the end might be useful - then you could choose to prune which tiles you didn't want to represent.  NBT/JSON Comment lines? Is that a thing?

**Comment by generrosity** [comment] 2019-01-23 06:34
Yea nah - JSON specifically doesn't allow inter-element creativeness. People have tried to make a element "__comment":"foobar" a commonality but there is no consensus

Sweet. Thank you both for giving this suggestion a read - is cool stuff you people have been putting together

**Comment by MichaelHillcox** [comment] 2019-05-28 09:59
I think we discussed this in our Discord and agreed that having this is a good idea but it'll be done by creating a block in game that acts like the Angle block from EU2 where when you hit it, it'll break instantly but it'll also not drop anything meaning that there is no way to use this to the players advantage. It'll also be ugly by design 👍

**Comment by generrosity** [comment] 2019-05-28 12:28
Perfect! Great to hear it's getting a look at

**Comment by MajorTuvok** [comment] 2019-05-28 19:24
We should try to make pasting these placeholders a client side config-option though... Some people might not want to remove these blocks all the time.

**Comment by MichaelHillcox** [comment] 2019-08-07 15:59
@MajorTuvok can we close this now as we're supporting tiles?

**Comment by MajorTuvok** [comment] 2019-08-07 15:59
Yes, I think so too

**Closed by MajorTuvok** 2019-08-07 15:59 UTC
Labels: 1.14, enhancement
