### ISSUE TITLE
Error during common setup phase

### ISSUE THREAD

**Issue by MeinKraft** [Direwolf20-MC/BuildingGadgets#349] opened 2019-08-26 00:03 UTC
Forge 28.0.55
BuildingGadget 3.0.3

Even with only BuildingGadgets mod installed, getting "Error during common setup phase"

Latest.Log https://pastebin.com/DhqddS6u

**Comment by MajorTuvok** [comment] 2019-08-26 05:26
Duplicate of #347

**Closed by MajorTuvok** 2019-08-26 05:26 UTC
