### ISSUE TITLE
1.15.2 additional keybinds dont work

### ISSUE THREAD

**Issue by redgoblin88** [Direwolf20-MC/BuildingGadgets#488] opened 2020-06-21 13:11 UTC
if you have a keyboard or mouse with additional, programable function keys (F15+), then when re-binding the gadget to any of them, it wont work, like it wont open the radial menu or the function wont work...

this was also reported for 1.14 https://github.com/Direwolf20-MC/BuildingGadgets/issues/406

Gadgets: 3.3.5
Forge: 31.2.9
(do note that i am also using optifine: U-G1-pre21, however i dont think this would cause conflicts regarding keybinds?)

**Comment by MichaelHillcox** [comment] 2020-06-22 06:46
I am very curious if this is also an issue with other mods as we're using a pretty typical way of setting up keybindings.

**Comment by MichaelHillcox** [comment] 2020-10-29 15:48
This would appear to be an MC specific issue that was resolved in 1.16.2+. As we don't rely on any keys that the game uses, and thus it doesn't crash the game, I'm going to close this in hope that it's resolvd in 1.16. Sorry that I can't be much help here but we truely are using natively implemented systems and don't have much control around the cause of this issue.

**Closed by MichaelHillcox** 2020-10-29 15:48 UTC
Labels: 1.15, bug
