### ISSUE TITLE
Bill of Materials

### ISSUE THREAD

**Issue by generrosity** [Direwolf20-MC/BuildingGadgets#213] opened 2019-02-02 20:57 UTC
Would it be viable to add a Bill of Materials button? Pretty much just the hover text of the gadget as a copy-to-clipboard feature so you can have it on the side to refer to.

The people on the reddit forum have [been arranging](https://www.reddit.com/r/9x9/comments/aigr4l/meta_subreddit_guidelines/) a set of guidelines for sharing templates - and while I know 'web upload' [like VanillaFix](https://github.com/DimensionalDevelopment/VanillaFix/blob/master/src/main/java/org/dimdev/utils/HasteUpload.java) isn't occurring, this would also assist with asserting;

* Name of mods included
* final outer dimensions, and full material cost.

It would be handy in many way to have a paste of the BoM that you are already generating on the tooltip.

Similar BOM tasks and utilities could combine into an upgraded manager block.

**Comment by MajorTuvok** [comment] 2019-02-02 22:07
Duplicate of #172 (though I did miss the dimensions and material cost their)

**Comment by generrosity** [comment] 2019-02-02 22:13
Ah! Indeed 💚 This also adds "clipboard' to the 'show these strings' solutions which is different to listed suggestions so far.

Cheers!

**Comment by MajorTuvok** [comment] 2019-02-02 22:32
Ok

**Comment by MajorTuvok** [comment] 2019-02-02 22:40
I think I've got the information over...

**Closed** 2019-02-02 23:00 UTC
Labels: enhancement
