### ISSUE TITLE
1.12.2 Forge 2757 - Crash after switching to the Gadget in the Toolbar

### ISSUE THREAD

**Issue by darkman1984** [Direwolf20-MC/BuildingGadgets#66] opened 2018-08-22 00:25 UTC
Crash after switching to the Gadget in the Toolbar

Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.direwolf20.buildinggadgets.tools.GadgetUtils.getAnchor(GadgetUtils.java:116)
	at com.direwolf20.buildinggadgets.tools.ToolRenders.renderBuilderOverlay(ToolRenders.java:43)
	at com.direwolf20.buildinggadgets.ClientProxy.renderWorldLastEvent(ClientProxy.java:62)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_174_ClientProxy_renderWorldLastEvent_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:181)
	at sun.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:653)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1946)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by MajorTuvok** [comment] 2018-08-22 06:28
Which Building Gadgets version are you using? Because according to the current Code the Line throwing the NPE simply initilises an ArrayList without any Parameters and therefore [cannot throw an NPE](https://github.com/Direwolf20-MC/BuildingGadgets/blob/ac3654abc428fd6c8057e020a6a29e9c4b5da90d/src/main/java/com/direwolf20/buildinggadgets/tools/GadgetUtils.java#L116). I guess that you are therefore not using the current version of BuildingGadgets?

Anyway, pretty close to it is an unchecked [`stack.getTagCompound()`](https://github.com/Direwolf20-MC/BuildingGadgets/blob/ac3654abc428fd6c8057e020a6a29e9c4b5da90d/src/main/java/com/direwolf20/buildinggadgets/tools/GadgetUtils.java#L115) which might cause an NPE, but after looking through the current Code, if the stack would have been null, then there would have been a NPE in ClientProxy, because ClientProxy calls all the [`stack.getItem()`](https://github.com/Direwolf20-MC/BuildingGadgets/blob/ac3654abc428fd6c8057e020a6a29e9c4b5da90d/src/main/java/com/direwolf20/buildinggadgets/ClientProxy.java#L70-L75)  without checking for nullability of the stack first.

This results in a NotNull stack in GadgetUtils#getAnchor - I therefore presume that this issue is solved in the current version. Please confirm with a the current version (If it is still present, then this should allow to get the correct NPE line).

**Comment by MajorTuvok** [comment] 2018-08-22 06:29
I just found an old related issue with the same crash(#55) - I guess that this is already solved.

**Comment by darkman1984** [comment] 2018-08-22 11:17
Version 1.6.2

**Comment by Direwolf20-MC** [comment] 2018-08-22 23:33
Should be fixed in 2.0 :)

**Closed by Direwolf20-MC** 2018-08-22 23:33 UTC

**Comment by Phylogeny** [comment] 2019-02-02 13:21
Duplicate of #55
