### ISSUE TITLE
"Undo" undoes too much

### ISSUE THREAD

**Issue by Porcy** [Direwolf20-MC/BuildingGadgets#455] opened 2020-03-21 01:31 UTC
Forge:14.23.5.2847
Building Gadgets:2.8.2
I built a staircase with dirt. Then pressed my "Undo" button. The dirt of the stair went back in my inventory: good. But I also got a lot more dirt than the blocks placed. I discovered the inside of the hill (made of dirt) also got "excavated" by the undo function, thus the dirt surplus.
(Edit): Upon further testing, it appears that you don't need to build anything. If you hit "Undo", it will excavate blocks from around you. I destroyed part of my hill testing this :(

**Comment by MichaelHillcox** [comment] 2020-07-15 20:55
I actually can't reproduce this very easily. I'm going to close this as it's been a while but if you can find a way to get it to happen almost every time then I'd happily take another look at it.

**Closed by MichaelHillcox** 2020-07-15 20:55 UTC
Labels: 1.12, bug
